# Generated by Django 4.1.7 on 2023-03-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_task_start_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="desc",),
    ]
