# Generated by Django 4.1.7 on 2023-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_task_date_cc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_cc",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
